# Copyright 2023 OmniSafe Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

defaults:
  seed: 0
  env_name: Walker2d-v2
  env_parallel_num: 1
  train_cfgs:
    device: cuda:0
    total_steps: 1000000
    dataset: walker2d_full_replay-v2
    evaluate_epoisodes: 0
    lr: 0.0005
    gradient_accumulate_every: 2
    obs_history_length: 1
  algo_cfgs:
    gamma: 0.99
    batch_size: 128
    steps_per_epoch: 1000
    horizon: 64
    n_diffusion_steps: 10
    noise_model: "DiT"

  logger_cfgs:
    use_tensorboard: True
    save_model_freq: 1000
    log_dir: "./runs"
  model_cfgs:
    returns_condition: True
    diffuser_model:
      train_only_inv: False
      loss_weights: None
      loss_discount: 1
      predict_epsilon: True
      hidden_dim: 128
      clip_denoised: True
      condition_guidance_w: 1.0
    temporalU_model:
      dim_mults: [ 1, 4, 8 ]
      calc_energy: False
      dim: 64
      condition_dropout: 0.25
    DiT:
      hidden_dim: 128
      cond_dim: 1
      n_heads: 4
      depth: 8
      dropout: 0.1

  dataset_cfgs:
    use_padding: True
    include_returns: True
    obs_normalize: False
    reward_normalize: False
  evaluate_cfgs:
    returns: 0.9
    multi_step_pred: 20
    evaluate_model_index: 80000



